// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module qbufGen (
        ap_ready,
        qid_V_read,
        hIndexPre2,
        ky,
        kx,
        cig,
        qod_V_read,
        ap_return
);


output   ap_ready;
input  [11:0] qid_V_read;
input  [15:0] hIndexPre2;
input  [5:0] ky;
input  [4:0] kx;
input  [12:0] cig;
input  [23:0] qod_V_read;
output  [23:0] ap_return;

wire   [0:0] tmp_fu_74_p2;
wire   [0:0] tmp_s_fu_80_p2;
wire   [4:0] tmp_3_fu_92_p1;
wire   [7:0] tmp_6_fu_102_p4;
wire   [4:0] tmp_4_fu_96_p2;
wire   [12:0] tmp_1_fu_112_p3;
wire   [0:0] tmp_2_fu_120_p2;
wire   [0:0] or_cond_fu_86_p2;
wire   [23:0] tmp_5_fu_132_p1;
wire   [0:0] or_cond2_fu_126_p2;
wire   [23:0] tmp_7_fu_136_p2;

assign ap_ready = 1'b1;

assign ap_return = ((or_cond2_fu_126_p2[0:0] === 1'b1) ? tmp_5_fu_132_p1 : tmp_7_fu_136_p2);

assign or_cond2_fu_126_p2 = (tmp_2_fu_120_p2 & or_cond_fu_86_p2);

assign or_cond_fu_86_p2 = (tmp_s_fu_80_p2 | tmp_fu_74_p2);

assign tmp_1_fu_112_p3 = {{tmp_6_fu_102_p4}, {tmp_4_fu_96_p2}};

assign tmp_2_fu_120_p2 = ((tmp_1_fu_112_p3 == 13'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_92_p1 = cig[4:0];

assign tmp_4_fu_96_p2 = (tmp_3_fu_92_p1 | kx);

assign tmp_5_fu_132_p1 = qid_V_read;

assign tmp_6_fu_102_p4 = {{cig[12:5]}};

assign tmp_7_fu_136_p2 = (tmp_5_fu_132_p1 + qod_V_read);

assign tmp_fu_74_p2 = ((ky == 6'd0) ? 1'b1 : 1'b0);

assign tmp_s_fu_80_p2 = ((hIndexPre2 == 16'd0) ? 1'b1 : 1'b0);

endmodule //qbufGen
