/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/AESL_axi_master_FIN_DDR.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/AESL_axi_master_FOUT_DDR.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/AESL_axi_master_WEIGHTS_DDR.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/AESL_axi_slave_axilite.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/axibus2rambus.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/axvalid_ctrl.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/ceil_power_of_2.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cm_cnt.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cnna.autotb.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cnna.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cnna_axilite_s_axi.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cnna_FIN_DDR_m_axi.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cnna_FOUT_DDR_m_axi.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/cnna_WEIGHTS_DDR_m_axi.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/glbl.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/load_all_weights.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/load_bias.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/load_weights.v
/media/cqiu/e/work/prj/AIPrj/sim/sim_cnna190717a/rtl/sim/verilog/spram.v
